name: path_parsing
version: 0.2.0-nullsafety.0
description: >
  A Dart library to help with SVG Path parsing and code generation.  Used by Flutter SVG.
homepage: https://github.com/dnfield/dart_path_parsing

dependencies:
  vector_math: ^2.1.0-nullsafety.3
  meta: ^1.3.0-nullsafety.4

dev_dependencies:
  path: ^1.8.0-nullsafety.1
  test: ^1.16.0-nullsafety.7

environment:
  sdk: '>=2.11.0-260.0.dev <3.0.0'
