name: path_parsing
version: 0.1.4
description: >
  A Dart library to help with SVG Path parsing and code generation.  Used by Flutter SVG.
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/dart_path_parsing

dependencies:
  vector_math: 2.1.0-nullsafety.3
  meta: 1.3.0-nullsafety.4

dev_dependencies:
  path: 1.8.0-nullsafety.1
  test: 1.16.0-nullsafety.5

environment:
  sdk: '>=2.10.0-56.0.dev <3.0.0'
