name: path_parsing
version: 1.0.0
description: >
  A Dart library to help with SVG Path parsing and code generation.  Used by Flutter SVG.
homepage: https://github.com/dnfield/dart_path_parsing

dependencies:
  meta: ^1.3.0

dev_dependencies:
  path: ^1.8.0
  test: ^1.16.0

environment:
  sdk: '>=2.12.0 <3.0.0'
